library(shiny)
library(knitr)
library(ggplot2)
library(dplyr)
require(gsubfn)
require(rvest)
library(readr)
require(xml2)
require(ggplot2)
library(sp)
library(maptools)
library(reshape2)
library(digest)

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding = "UTF-8")